run:
  timeout: 5m
  modules-download-mode: readonly
  skip-dirs:
    - vendor
  skip-files:
    - ".*\\.pb\\.go$"

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/RRethy/eddie)
  gofumpt:
    lang-version: "1.23"
  govet:
    enable-all: true
    disable:
      - shadow
  staticcheck:
    checks: ["all"]

linters:
  enable:
    - gofumpt
    - goimports
    - govet
    - staticcheck
    - ineffassign
    - misspell
    - gocritic
    - gci
    - unconvert
    - unparam
    - unused
    - errcheck
    - gosimple
  disable:
    - gochecknoinits
